name: Test bug

on:
  workflow_dispatch:
    inputs:
      hello:
        default: world
        description: "Hello world"
        type: string
      choice:
        default: 1
        description: "Choice"
        type: choice
        options:
          - 1
          - 2
          - 3

jobs:
  test:
    uses: ./.github/workflows/callable.yml
    with:
      hello: ${{ inputs.hello }}
      choice: ${{ inputs.choice }}